strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'windows-2019'

trigger:
- master

pool:
  vmImage: $(imageName)

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
steps:
- pwsh: ./build.ps1 -t ci
  displayName: 'Build'
  env: 
    kek: $(kek)

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

#- task: NuGetCommand@2
#  displayName: 'NuGet push'
#  inputs:
#    command: push
#    publishVstsFeed: 'FluentValidation-ci'
#    allowPackageConflicts: true
#    packagesToPush: '$(Build.SourcesDirectory)/.build/packages/*.nupkg'
#  condition: eq( variables['Agent.OS'], 'Windows_NT' )
