pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

variables:
  version.major: 11
  version.minor: 10
  version.patch: 0
  version.revision: $[ counter(format('{0}-{1}.{2}.{3}', variables['system.definitionId'], variables['version.major'], variables['version.minor'], variables['version.patch']), 0) ]

name: $(version.major).$(version.minor).$(version.patch)-assurecare.$(version.revision)

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet build

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    nobuild: true
    arguments: --no-restore

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    arguments: --no-restore

- task: DotNetCoreCLI@2
  displayName: dotnet push
  inputs:
    command: push
    publishVstsFeed: MedCompass_Web
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
