name: "\U0001F41B Bug Report"
description: "Report a reproducible bug in FluentValidation. Also use this template if you're having trouble upgrading from version 10.x 
to 11.x"
body:
- type: markdown
  attributes:
    value: | 
      Thanks for taking the time to file a bug report! Before filling out a new issue, please first check to see if your question has been answered in an existing issue, or in the project documentation at [https://docs.fluentvalidation.net](https://docs.fluentvalidation.net)
      
      **Please note** FluentValidation is supported for free on a voluntary basis. If you use FluentValidation please [sponsor the project](https://github.com/sponsors/JeremySkinner) so that its development can continue. Bug reports from sponsors will be prioritised.
      
      Please take the time to fill in this form as completely as possible. If you leave out sections there is a high likelihood your issue will be closed.
- type: input
  attributes:
    label: FluentValidation version
    description: Which version of FluentValidation are you using? Please note that only FluentValidation versions 11.x and 10.x are supported. Issues related to older versions will be closed. 
  validations:
    required: true
- type: input
  attributes:
    label: ASP.NET version
    description: If you are using FluentValidation with ASP.NET, please provide the version of ASP.NET that you're using (eg .NET Core 3.1, .NET 6 etc). Leave this blank if you're not using ASP.NET.
- type: textarea
  attributes:
    label: Summary
    description: A clear and concise description of the issue that you're having.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: "Please include all the steps necessary to reproduce the issue, including any sample code (preferably in the form of a runnable unit test). Alternatively, please provide a link to a *minimal* sample project. Please do not include screenshots of code."  
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Please ensure that any code samples are readable and [properly formatted as code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).
      
      **Please realise that it is up to you to debug your code thoroughly. Be as certain as possible that the bug is with FluentValidation, and not with your own code, prior to opening an issue.**
