blank_issues_enabled: false
contact_links: 
  - name: Issue tracker temporarily offline
    url: "https://github.com/FluentValidation/FluentValidation/issues/2332"
    about: The issue tracker is temporarily offline as I'm not currently able to monitor it due to personal reasons. It will be re-enabled in the future. Thank you for your understanding. 
