on: [push, pull_request]

jobs:
  qodana-scan:
    name: Qodana Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          upload-result: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
